Rd 308 utilities plugin docs wrapup
cloudify-cosmo/docs.getcloudify.org pull request #1579
Opened 2020-11-26 14:56 UTC by AdarShaked

2020-11-26 17:05 UTC, EarthmanT approved these changes

2020-11-29 09:11 UTC, EarthmanT approved these changes

2020-11-29 12:07 UTC, EarthmanT approved these changes

2020-11-29 16:44 UTC, ofercloudify requested changes

2020-11-29 16:44 UTC, ofercloudify commented on content/working_with/official_plugins/Configuration/utilities/files.md
> +If used in order to transfer file to remote host that defined in the blueprint use `cloudify.relationships.contained_in` relationship (see [openstack-blueprint.yaml](https://github.com/cloudify-commu
```suggestion
For file transfer to a remote host defined in the blueprint, use `cloudify.relationships.contained_in` relationship (see [openstack-blueprint.yaml](https://github.com/cloudify-community/blueprint-examples/blob/master/utilities-examples/cloudify_files/openstack-blueprint.yaml) example). 
```

2020-11-29 16:44 UTC, ofercloudify commented on content/working_with/official_plugins/Configuration/utilities/ftp.md
> +The FTP utility allows you to Upload files by FTP to remote host.
```suggestion
The FTP utility allows you to upload files by FTP to a remote host.
```

2020-11-29 16:44 UTC, ofercloudify commented on content/working_with/official_plugins/Configuration/utilities/ftp.md
> +This is node type that describes the files to transfer and the FTP server details.
```suggestion
This node type describes the files to transfer and the FTP server details.
```

2020-11-29 16:44 UTC, ofercloudify commented on content/working_with/official_plugins/Configuration/utilities/suspend.md
> +* `include_instances` parameter for limit list of instances where we call operations.
Please rephrase. I could not understand this one to suggest an alternative :)

2020-11-29 16:44 UTC, ofercloudify commented on content/working_with/official_plugins/Configuration/utilities/suspend.md
> +* `skip_actions` node property check for disable specific actions on node.
```suggestion
* `skip_actions` node property check for disabling specific actions on the node.
```

2020-11-29 16:44 UTC, ofercloudify commented on content/working_with/official_plugins/Configuration/utilities/suspend.md
> +* `Backup` has such meaning - some object contain full copy of original object and can
```suggestion
* `Backup` has such meaning - some objects contain a full copy of the original object and can
```

2020-11-29 16:44 UTC, ofercloudify commented on content/working_with/official_plugins/Configuration/utilities/suspend.md
> +   be used after remove original object.
```suggestion
   be used after removing the original object.
```

2020-11-29 16:44 UTC, ofercloudify commented on content/working_with/official_plugins/Configuration/utilities/suspend.md
> +* `Snapshot` has such meaning - some objects that directly connected to parent object
Unclear. can you please rephrase?

2020-11-29 16:44 UTC, ofercloudify commented on content/working_with/official_plugins/Configuration/utilities/suspend.md
> +`Backup` workflow has such parameters:
```suggestion
The `Backup` workflow has the following parameters:
```

2020-11-29 16:44 UTC, ofercloudify commented on content/working_with/official_plugins/Configuration/utilities/suspend.md
> +Meaning of each params depends on plugin implementation and can have different sense
```suggestion
The meaning of each param depends on plugin implementation and can have a different sense
```

2020-11-29 16:44 UTC, ofercloudify commented on content/working_with/official_plugins/Configuration/utilities/suspend.md
> +   things like images, volume snapshots or backups. Name of resulted object is
```suggestion
   things like images, volume snapshots, or backups. The name of a resulted object is
```

2020-11-29 16:44 UTC, ofercloudify commented on content/working_with/official_plugins/Configuration/utilities/suspend.md
> +   something like ```<object type>-<original object id>-<backup name>```. We need such
```suggestion
   something like ```<object type>-<original object id>-<backup name>```. We need that
```

2020-11-29 16:44 UTC, ofercloudify commented on content/working_with/official_plugins/Configuration/utilities/suspend.md
> +   because result of VM snapshot, VM backup and Volume backup
```suggestion
   because the result of VM snapshot, VM backup, and Volume backup
```

2020-11-29 16:44 UTC, ofercloudify commented on content/working_with/official_plugins/Configuration/utilities/suspend.md
> +   is image. So we need some information in name for understand what id parent object
```suggestion
   is an image, hence we need some information in the name to understand the id of the parent object
```

2020-11-29 16:44 UTC, ofercloudify commented on content/working_with/official_plugins/Configuration/utilities/suspend.md
> +values and is passing this values without any changes. Cloudify plugins is not
```suggestion
values and is passing these values without any changes. The plugin is not
```

2020-11-29 16:44 UTC, ofercloudify commented on content/working_with/official_plugins/Configuration/utilities/suspend.md
> +responsible for remove all old backups or snapshots by rotation field.
```suggestion
responsible for removing all old backups or snapshots by rotation field.
```

2020-11-29 16:44 UTC, ofercloudify commented on content/working_with/official_plugins/Configuration/utilities/suspend.md
> +`Restore` workflow has such parameters:
```suggestion
The `Restore` workflow has the following parameters:
```

2020-11-29 16:44 UTC, ofercloudify commented on content/working_with/official_plugins/Configuration/utilities/suspend.md
> +Both parameters have same meaning as in backup workflow.
```suggestion
Both parameters have the same meaning as in backup workflow.
```

2020-11-29 16:44 UTC, ofercloudify commented on content/working_with/official_plugins/Configuration/utilities/suspend.md
> +* Volumes: if customer have tried to restore from snapshot - we show warning and
```suggestion
* Volumes: if the customer has tried to restore from a snapshot - we show a warning and
```

2020-11-29 16:44 UTC, ofercloudify commented on content/working_with/official_plugins/Configuration/utilities/suspend.md
> +   ignore action. In case when customer have used backup - we ask openstack for
```suggestion
   ignore the action. In case the customer has used backup - we ask OpenStack to
```

2020-11-29 16:44 UTC, ofercloudify commented on content/working_with/official_plugins/Configuration/utilities/suspend.md
> +   restore volume from backup. Such logic is limitation of openstack, so we can
```suggestion
   restore the volume from backup. Such logic is a limitation of OpenStack, hence we can
```

2020-11-29 16:44 UTC, ofercloudify commented on content/working_with/official_plugins/Configuration/utilities/suspend.md
> +`Remove backup` workflow has such parameters:
```suggestion
The `Remove backup` workflow has the following parameters:
```

2020-11-29 16:44 UTC, ofercloudify commented on content/working_with/official_plugins/Configuration/utilities/suspend.md
> +Both parameters have same meaning as in backup workflow.
```suggestion
Both parameters have the same meaning as in backup workflow.
```

2020-11-29 16:44 UTC, ofercloudify commented on content/working_with/official_plugins/Configuration/utilities/suspend.md
> +For openstack:
```suggestion
For OpenStack:
```

2020-11-30 09:19 UTC, ofercloudify approved these changes

2020-11-30 09:19 UTC, merged