Adding vmware stack documentation
cloudify-cosmo/docs.getcloudify.org pull request #1674
Opened 2021-01-18 13:27 UTC by alexmolev

2021-01-22 16:58 UTC, natishalom commented
When is this planned to go live?

2021-01-24 10:00 UTC, ofercloudify requested changes

2021-01-24 10:00 UTC, ofercloudify commented on content/bestpractices/vmware_docs.md
> +* [Cloudify example with vSphere and VRO](https://vimeo.com/448587029)
```suggestion
* [vSphere and VRO](https://vimeo.com/448587029)
```

2021-01-24 10:00 UTC, ofercloudify commented on content/bestpractices/vmware_docs.md
> +* [Cloudify example with vSphere and NSX-T](https://vimeo.com/457711864)
```suggestion
* [vSphere and NSX-T](https://vimeo.com/457711864)
```

2021-01-24 11:55 UTC, ofercloudify approved these changes

2021-01-24 11:55 UTC, merged