Add more detailes to the level-6 EaaS use case
cloudify-cosmo/docs.getcloudify.org pull request #1675
Opened 2021-01-19 07:15 UTC by alexmolev

2021-01-21 07:30 UTC, ofercloudify requested changes

2021-01-21 07:30 UTC, ofercloudify commented on content/trial_getting_started/examples/eaas/_index.md
> +In a case of development environment were using a single instance per service and can also run all those services in a single VM. In the production case were using a fully managed version of those se
```suggestion
In the case of a development environment, we are using a single instance per service and can also run all those services in a single VM. In the production case, we are using a fully managed version of those services with EKS as the Kubernetes cluster, RDS as the managed DB, and S3 as the managed storage services as illustrated in the diagram below.
```

2021-01-21 07:30 UTC, ofercloudify commented on content/trial_getting_started/examples/eaas/_index.md
> +In this example we use a stack based on Kubernetes , Postgress as the DB and S3 as the storage system. Each of those services is referenced by a seperate service component.  The exact blueprint per c
```suggestion
In this example, we use a stack based on Kubernetes, Postgress as the DB, and S3 as the storage system. Each of those services is referenced by a separate service component.  The exact blueprint per component is determined at runtime based on the environment type.
```

2021-01-21 07:32 UTC, ofercloudify commented
I noticed you added several png files that are not used in the article. any reason for that?

2021-01-21 08:09 UTC, natishalom commented
> I noticed you added several png files that are not used in the article. any reason for that?

There should be a single image not multiple images

2021-01-21 09:39 UTC, natishalom commented
@ofercloudify see the staging version - it shows a single image https://docs.cloudify.co/staging/Getting-Started-Level-6-update/trial_getting_started/examples/eaas/

2021-01-25 13:00 UTC, natishalom commented
@ofercloudify fixed the additional files with @alexmolev help ..

2021-01-25 14:38 UTC, ofercloudify approved these changes

2021-01-25 14:47 UTC, merged