RD-1706-Fabric-plugin-non-recoverable-errors
cloudify-cosmo/docs.getcloudify.org pull request #1748
Opened 2021-03-21 09:35 UTC by ahmadiesa-abu

added the new input description

2021-03-29 08:25 UTC, EarthmanT approved these changes

2021-04-21 12:57 UTC, ofercloudify requested changes

2021-04-21 12:57 UTC, ofercloudify commented on content/working_with/official_plugins/Configuration/fabric.md
> +Fabric might generate exception if there is a problem with the execution. By default all of that exceptions are considered recoverable but you can control that with a provided list of error codes to
```suggestion
Fabric might generate an exception if there is a problem with the execution. By default, all of the exceptions are considered recoverable but you can control that with a provided list of error codes to change that to be non-recoverable. The `non_recoverable_error_exit_codes` input is a list of `exit_codes`.
```

2021-04-21 13:32 UTC, ofercloudify approved these changes

2021-04-22 06:52 UTC, merged