add eks auth docs
cloudify-cosmo/docs.getcloudify.org pull request #1758
Opened 2021-03-29 13:56 UTC by AdarShaked

spaces

one more space

2021-03-29 16:10 UTC, EarthmanT submitted a review, later dismissed

2021-03-31 17:54 UTC, ofercloudify requested changes

2021-03-31 17:54 UTC, ofercloudify commented on content/working_with/official_plugins/Orchestration/helm.md
> +When using EKS, create kubeconfig as explained in [AWS docs](https://docs.aws.amazon.com/eks/latest/userguide/create-kubeconfig.html#create-kubeconfig-manually) using AWS cli (not aws-iam-authenticat
```suggestion
When using EKS, create kubeconfig as explained in [AWS docs](https://docs.aws.amazon.com/eks/latest/userguide/create-kubeconfig.html#create-kubeconfig-manually) using the AWS CLI (not aws-iam-authenticator).
```

2021-04-01 05:54 UTC, AdarShaked commented on content/working_with/official_plugins/Orchestration/helm.md
> +When using EKS, create kubeconfig as explained in [AWS docs](https://docs.aws.amazon.com/eks/latest/userguide/create-kubeconfig.html#create-kubeconfig-manually) using AWS cli (not aws-iam-authenticat
Done

2021-04-01 06:27 UTC, ofercloudify approved these changes

2021-04-01 06:28 UTC, merged