Document K8s CRDs and COs
cloudify-cosmo/docs.getcloudify.org pull request #1759
Opened 2021-03-29 14:33 UTC by EarthmanT

2021-03-29 14:49 UTC, AdarShaked approved these changes

2021-03-29 14:49 UTC, AdarShaked commented on content/working_with/official_plugins/Orchestration/kubernetes.md
> +The Cloudify Kubernetes Plugin supports creating and using [CustomResourceDefinition](https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/)s.
[CustomResourceDefinitions] ?

2021-03-29 15:29 UTC, EarthmanT commented on content/working_with/official_plugins/Orchestration/kubernetes.md
> +The Cloudify Kubernetes Plugin supports creating and using [CustomResourceDefinition](https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/)s.
No

2021-03-31 17:05 UTC, ofercloudify requested changes

2021-03-31 17:05 UTC, ofercloudify commented on content/working_with/official_plugins/Orchestration/kubernetes.md
> +The Cloudify Kubernetes Plugin supports creating and using [CustomResourceDefinition](https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/)s.
```suggestion
The {{< param product_name >}} Kubernetes Plugin supports creating and using [CustomResourceDefinition](https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/)s.
```

2021-03-31 17:05 UTC, ofercloudify commented on content/working_with/official_plugins/Orchestration/kubernetes.md
> +Cloudify needs these keys in order to identify the resource as a usage of a **CustomDefinedResource**.
```suggestion
{{< param product_name >}} needs these keys in order to identify the resource as a usage of a **CustomDefinedResource**.
```

2021-05-04 18:19 UTC, closed without merging