Bump cfy-cluster-manager to v1.0.9
cloudify-cosmo/docs.getcloudify.org pull request #1817
Opened 2021-05-02 14:41 UTC by YoniItzhak

2021-05-02 14:42 UTC, YoniItzhak commented on content/install_maintain/installation/cfy-cluster-manager.md
> +The {{< param product_name >}} cluster can be upgraded from v5.1.0 to higher versions using the following command:
@ofercloudify, I wrote "higher versions", but we can also specify the specific versions allowed for upgrading.

2021-05-03 06:06 UTC, ofercloudify requested changes

2021-05-03 06:06 UTC, ofercloudify commented on content/install_maintain/installation/cfy-cluster-manager.md
> +The {{< param product_name >}} cluster can be upgraded from v5.1.0 to higher versions using the following command:
```suggestion
The {{< param product_name >}} cluster can be upgraded from v5.1.0 (or any later release) to a more recent version using the following command:
```

2021-05-03 06:21 UTC, ofercloudify approved these changes

2021-05-03 06:26 UTC, merged