first draft starlingx
cloudify-cosmo/docs.getcloudify.org pull request #1858
Opened 2021-05-31 16:17 UTC by EarthmanT

2021-06-01 08:09 UTC, ofercloudify requested changes

2021-06-01 08:09 UTC, ofercloudify commented on content/working_with/official_plugins/Orchestration/starlingx.md
> +  * `discover_and_deploy`: Discover a System's subclouds and create deployments for all of the subclouds. One should use default values for all workflow parameters. The workflow will create a deploym
I think we shoudl also mention the automatic assignment of Site per discovered WRCP, and the automatic assignment of labels.

2021-06-01 08:09 UTC, ofercloudify commented on content/working_with/official_plugins/Orchestration/starlingx.md
> +**Workflows**
Is the logic regarding IPv6/4 and https relevant here at all or is it Blueprint only?

2021-06-01 11:47 UTC, mpeters-wrs commented
Would it be more appropriate to have the Starlingx plugin under the Infrastructure Plugins rather than Orchestration?

2021-06-01 12:17 UTC, EarthmanT commented
> Would it be more appropriate to have the Starlingx plugin under the Infrastructure Plugins rather than Orchestration?
@mpeters-wrs 
@ofercloudify What do you think?
I put it in orchestration because we are not actually modifying infra. Please let me know what you decide.

2021-06-01 12:51 UTC, ofercloudify commented
I second @mpeters-wrs opinion here. I believe it should go under infrastructure.
While at the moment we do not modify anything within the WR systems, we certainly may in the future, and conceptually I find it closer to infra than orchestration.

2021-06-01 12:53 UTC, EarthmanT commented
@ofercloudify @mpeters-wrs moved the page to be under infrastructure as requested.

2021-06-02 14:37 UTC, ofercloudify requested changes

2021-06-02 14:37 UTC, ofercloudify commented on content/working_with/official_plugins/Infrastructure/starlingx.md
> +  - Discover all subclouds that are managed by the system controller (parent).
Missing one newline before line 17 to get the list displayed properly.

2021-06-02 14:37 UTC, ofercloudify commented on content/working_with/official_plugins/Infrastructure/starlingx.md
> +To discover subclouds, execute the `discover_and_deploy` workflow. This workflow performs the following tasks:
```suggestion
To discover subclouds, execute the `discover_and_deploy` workflow over a Controller deployment. This workflow performs the following tasks:
```

2021-06-02 14:37 UTC, ofercloudify commented on content/working_with/official_plugins/Infrastructure/starlingx.md
> +**Runtime Properties**:
The flow also sets a site per Subcloud and adds it if it does not exist. not sure in which section but it is worth mentioning it here.

2021-06-06 14:18 UTC, ofercloudify approved these changes

2021-06-06 14:39 UTC, merged