RD-4726-create-a-workflow-for-tfsec
cloudify-cosmo/docs.getcloudify.org pull request #2202
Opened 2022-05-02 07:31 UTC by Nelynehemia

2022-05-02 13:52 UTC, EarthmanT requested changes

2022-05-02 13:52 UTC, EarthmanT commented on content/working_with/official_plugins/Orchestration/terraform.md
> +  * `terraform.tfsec`:   tfsec is a static analysis security scanner for your Terraform code. For example
Explain that this text should be in a YAML file, like "params.yaml".

2022-05-03 14:54 UTC, EarthmanT commented on content/working_with/official_plugins/Orchestration/terraform.md
> +  * `terraform.tfsec`:   TFSec is a static analysis security scanner for your Terraform code. Here is an example of a yaml file that can be used to call a command.
```suggestion
  * `terraform.tfsec`:   TFSec is a static analysis security scanner for your Terraform code. The following example can be used as a parameter file to the execute operation command:```

2022-05-08 07:13 UTC, MichaelShn approved these changes

2022-05-08 07:22 UTC, merged